spring:
  profiles:
    active: local
  application:
    name: estonian-crossword-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/crossword_db
    username: crossword_user
    password: strong_password
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  port: 8080

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:4200
    - http://localhost:5173

word-loader:
  files:
    - file: loomad.json
      category: LOOMAD
    - file: toit.json
      category: TOIT
    - file: ametid.json
      category: AMETID
    - file: kodu.json
      category: KODU
    - file: riigid.json
      category: RIIGID